# config.yml for Reminder plugin
# startOnLoad: When set to 'true', will begin processing reminders after seconds of delay specified by taskRate.
# tag:   The default text used when tag is not specified.
# delay: The default delay in minutes used when delay is not specified.
# rate:  The default rate in minutes used when rate is not specified. 0 = at taskRate.
# echo:  The default timed a reminder is echoed when echo is not specified. -1 = forever.
# maxRows: The maximum number of rows the list command will return.
# taskRate: The number of seconds delay and between reminder processing. Range 15 - 120.
# dbUrl:      URL of the MySQL database. i.e.: jdbc:mysql://localhost/Chrisbot
# dbUser:     Database username.
# dbPassword: Database password.

startOnLoad: false

tag: default
delay: 1
rate: 5
echo: 3

maxRows: 20

taskRate: 15

dbUrl: jdbc:mysql://localhost/Chrisbot
dbUser: root
dbPassword: root
