name: Reminder
author: Chrisbotcom
website: http://chrisbotcom.github.io/Reminder/
main: io.github.chrisbotcom.reminder.Reminder
version: 1.0
database: false
commands:
   reminder:
      aliases: [rem]
      description: Reminder plugin.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /help <command> [add|list|delete|update|setdefault|reload|stop|resume|time]
   reminder add:
      description: Add a reminder.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command> <player> "<message>" <seconds>|activate <yyyy-mm-dd HH:MM> [tag <tag>] [cooldown <seconds>] [frequency <seconds>] [count <count>]
   reminder list:
      description: List all reminders or reminders for a player and or tag.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command> [player <player>] [tag <text>]
   reminder delete:
      description: Delete a reminder by id or by player and/or tag.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command> [<id>]|[[player <player>] [tag '<text>']]
   reminder update:
      description: Update a reminder referenced by id.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command> <id> [player <player>] [message '<message>'] [delay <seconds>|activate <yyyy-mm-dd HH:MM>] [tag <text>] [cooldown <seconds>] [frequency <seconds>] [count <seconds>] 
   reminder setdefault:
      description: Sets the default for the given setting, saves it in settings.yml and activates the setting immediately.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command> [cooldown <seconds>] [frequency <seconds>] [count <count>] [tag '<text>'] [prefix '<text>']
   reminder reload:
      description: Reload settings.yml.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command>
   reminder stop:
      description: Stop all reminders.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command>
   reminder resume:
      description: Resume all reminders.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command>
   reminder time:
      description: Report server time.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command>
